### ISSUE TITLE
Conflict between biopython and ipykernel

### ISSUE THREAD

**Issue by Tuyt691** [biopython/biopython#5060]
Hello,

I am trying to run a class containing biopython methods. I want to use this class in a jupyter notebook.

`from Bio.PDB import PDBParser
import numpy as np
from scipy.spatial import Delaunay

class ProteinAtoms():
# etc...
`

In the Juputer notebook:
`import ProteinAtoms as PA

Pneumolysin = PA.ProteinAtoms('5aod')
`

At first, I run the notebook with an environment NOT containing the biopython package. I obviously get the error that the package biopython is not installed. But then, when I install biopython package, I get an error linked with the kernel: 
"The Kernel crashed while executing code in the current cell or a previous cell. 
Please review the code in the cell(s) to identify a possible cause of the failure. 
Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. 
View Jupyter [log](command:jupyter.viewOutput) for further details."

Specifications: 

- Working on Windows 11
- VsCode 1.102.0

 - Environment package list:
anyio                     4.10.0             pyhe01879c_0    conda-forge
argon2-cffi               25.1.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      25.1.0          py311h3485c13_0    conda-forge
arrow                     1.3.0              pyhd8ed1ab_1    conda-forge
asttokens                 3.0.0              pyhd8ed1ab_1    conda-forge
async-lru                 2.0.5              pyh29332c3_0    conda-forge
attrs                     25.3.0             pyh71513ae_0    conda-forge
babel                     2.17.0             pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.13.5             pyha770c72_0    conda-forge
biopython                 1.85            py311h3485c13_2    conda-forge
bleach                    6.2.0              pyh29332c3_4    conda-forge
bleach-with-css           6.2.0                h82add2a_4    conda-forge
brotli-python             1.1.0           py311h3e6a449_4    conda-forge
bzip2                     1.0.8                h0ad9c76_8    conda-forge
ca-certificates           2025.8.3             h4c7d964_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2025.8.3           pyhd8ed1ab_0    conda-forge
cffi                      1.17.1          py311h3485c13_1    conda-forge
charset-normalizer        3.4.3              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_1    conda-forge
comm                      0.2.3              pyhe01879c_0    conda-forge
debugpy                   1.8.16          py311h5dfdfe8_1    conda-forge
decorator                 5.2.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
exceptiongroup            1.3.0              pyhd8ed1ab_0    conda-forge
executing                 2.2.1              pyhd8ed1ab_0    conda-forge
fqdn                      1.5.1              pyhd8ed1ab_1    conda-forge
h11                       0.16.0             pyhd8ed1ab_0    conda-forge
h2                        4.3.0              pyhcf101f3_0    conda-forge
hpack                     4.1.0              pyhd8ed1ab_0    conda-forge
httpcore                  1.0.9              pyh29332c3_0    conda-forge
httpx                     0.28.1             pyhd8ed1ab_0    conda-forge
hyperframe                6.1.0              pyhd8ed1ab_0    conda-forge
idna                      3.10               pyhd8ed1ab_1    conda-forge
importlib-metadata        8.7.0              pyhe01879c_1    conda-forge
intel-openmp              2025.2.0           h57928b3_757    conda-forge
ipykernel                 6.30.1             pyh3521513_0    conda-forge
ipython                   9.5.0              pyh6be1c34_0    conda-forge
ipython_pygments_lexers   1.1.1              pyhd8ed1ab_0    conda-forge
ipywidgets                8.1.7              pyhd8ed1ab_0    conda-forge
isoduration               20.11.0            pyhd8ed1ab_1    conda-forge
jedi                      0.19.2             pyhd8ed1ab_1    conda-forge
jinja2                    3.1.6              pyhd8ed1ab_0    conda-forge
json5                     0.12.1             pyhd8ed1ab_0    conda-forge
jsonpointer               3.0.0           py311h1ea47a8_2    conda-forge
jsonschema                4.25.1             pyhe01879c_0    conda-forge
jsonschema-specifications 2025.9.1           pyhcf101f3_0    conda-forge
jsonschema-with-format-nongpl 4.25.1               he01879c_0    conda-forge
jupyter                   1.1.1              pyhd8ed1ab_1    conda-forge
jupyter-lsp               2.3.0              pyhcf101f3_0    conda-forge
jupyter_client            8.6.3              pyhd8ed1ab_1    conda-forge
jupyter_console           6.6.3              pyhd8ed1ab_1    conda-forge
jupyter_core              5.7.2           py311h1ea47a8_0    conda-forge
jupyter_events            0.12.0             pyh29332c3_0    conda-forge
jupyter_server            2.17.0             pyhcf101f3_0    conda-forge
jupyter_server_terminals  0.5.3              pyhd8ed1ab_1    conda-forge
jupyterlab                4.4.7              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.3.0              pyhd8ed1ab_2    conda-forge
jupyterlab_server         2.27.3             pyhd8ed1ab_1    conda-forge
jupyterlab_widgets        3.0.15             pyhd8ed1ab_0    conda-forge
krb5                      1.21.3               hdf4eb48_0    conda-forge
lark                      1.2.2              pyhd8ed1ab_1    conda-forge
libblas                   3.9.0           28_h576b46c_mkl    conda-forge
libcblas                  3.9.0           28_h7ad3364_mkl    conda-forge
libexpat                  2.7.1                hac47afa_0    conda-forge
libffi                    3.4.6                h537db12_1    conda-forge
liblapack                 3.9.0           28_hacfb0e4_mkl    conda-forge
liblzma                   5.8.1                h2466b09_2    conda-forge
libsodium                 1.0.20               hc70643c_0    conda-forge
libsqlite                 3.50.4               hf5d6505_0    conda-forge
libzlib                   1.3.1                h2466b09_2    conda-forge
markupsafe                3.0.2           py311h5082efb_1    conda-forge
matplotlib-inline         0.1.7              pyhd8ed1ab_1    conda-forge
mistune                   3.1.4              pyhcf101f3_0    conda-forge
mkl                       2020.4             hb70f87d_311    conda-forge
nbclient                  0.10.2             pyhd8ed1ab_0    conda-forge
nbconvert-core            7.16.6             pyh29332c3_0    conda-forge
nbformat                  5.10.4             pyhd8ed1ab_1    conda-forge
nest-asyncio              1.6.0              pyhd8ed1ab_1    conda-forge
notebook                  7.4.5              pyhd8ed1ab_0    conda-forge
notebook-shim             0.2.4              pyhd8ed1ab_1    conda-forge
numpy                     2.3.2           py311h80b3fa1_2    conda-forge
openssl                   3.5.2                h725018a_0    conda-forge
overrides                 7.7.0              pyhd8ed1ab_1    conda-forge
packaging                 25.0               pyh29332c3_1    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.5              pyhcf101f3_0    conda-forge
pickleshare               0.7.5           pyhd8ed1ab_1004    conda-forge
pip                       25.2               pyh8b19718_0    conda-forge
platformdirs              4.4.0              pyhcf101f3_0    conda-forge
prometheus_client         0.22.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.52             pyha770c72_0    conda-forge
prompt_toolkit            3.0.52               hd8ed1ab_0    conda-forge
psutil                    7.0.0           py311h3485c13_1    conda-forge
pure_eval                 0.2.3              pyhd8ed1ab_1    conda-forge
pycparser                 2.22               pyh29332c3_1    conda-forge
pygments                  2.19.2             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyh09c184e_7    conda-forge
python                    3.11.13         h3f84c4b_0_cpython    conda-forge
python-dateutil           2.9.0.post0        pyhe01879c_2    conda-forge
python-fastjsonschema     2.21.2             pyhe01879c_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python_abi                3.11                    6_cp311    conda-forge
pytz                      2025.2             pyhd8ed1ab_0    conda-forge
pywin32                   311             py311hefeebc8_1    conda-forge
pywinpty                  2.0.15          py311hda3d55a_0    conda-forge
pyyaml                    6.0.2           py311h5082efb_2    conda-forge
pyzmq                     27.1.0          py311hb77b9c8_0    conda-forge
referencing               0.36.2             pyh29332c3_0    conda-forge
requests                  2.32.5             pyhd8ed1ab_0    conda-forge
rfc3339-validator         0.1.4              pyhd8ed1ab_1    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rfc3987-syntax            1.1.0              pyhe01879c_1    conda-forge
rpds-py                   0.27.1          py311hf51aa87_1    conda-forge
send2trash                1.8.3              pyh5737063_1    conda-forge
setuptools                80.9.0             pyhff2d567_0    conda-forge
six                       1.17.0             pyhe01879c_1    conda-forge
sniffio                   1.3.1              pyhd8ed1ab_1    conda-forge
soupsieve                 2.8                pyhd8ed1ab_0    conda-forge
stack_data                0.6.3              pyhd8ed1ab_1    conda-forge
terminado                 0.18.1             pyh5737063_0    conda-forge
tinycss2                  1.4.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h2c6b04d_2    conda-forge
tomli                     2.2.1              pyhe01879c_2    conda-forge
tornado                   6.5.2           py311h3485c13_1    conda-forge
traitlets                 5.14.3             pyhd8ed1ab_1    conda-forge
types-python-dateutil     2.9.0.20250822     pyhd8ed1ab_0    conda-forge
typing-extensions         4.15.0               h396c80c_0    conda-forge
typing_extensions         4.15.0             pyhcf101f3_0    conda-forge
typing_utils              0.1.0              pyhd8ed1ab_1    conda-forge
tzdata                    2025b                h78e105d_0    conda-forge
ucrt                      10.0.26100.0         h57928b3_0    conda-forge
uri-template              1.3.0              pyhd8ed1ab_1    conda-forge
urllib3                   2.5.0              pyhd8ed1ab_0    conda-forge
vc                        14.3                h41ae7f8_31    conda-forge
vc14_runtime              14.44.35208         h818238b_31    conda-forge
vcomp14                   14.44.35208         h818238b_31    conda-forge
wcwidth                   0.2.13             pyhd8ed1ab_1    conda-forge
webcolors                 24.11.1            pyhd8ed1ab_0    conda-forge
webencodings              0.5.1              pyhd8ed1ab_3    conda-forge
websocket-client          1.8.0              pyhd8ed1ab_1    conda-forge
wheel                     0.45.1             pyhd8ed1ab_1    conda-forge
widgetsnbextension        4.0.14             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0              pyh7428d3b_8    conda-forge
winpty                    0.4.3                         4    conda-forge
yaml                      0.2.5                h6a83c73_3    conda-forge
zeromq                    4.3.5                h5bddc39_9    conda-forge
zipp                      3.23.0             pyhd8ed1ab_0    conda-forge
zstandard                 0.24.0          py311h2d646e2_1    conda-forge
zstd                      1.5.7                hbeecb71_2    conda-forge

**Comment by OWissett** [comment]
I've had the kernel crash before, normally just restarting the notebook's kernel should fix this. If you are installing new packages you must restart the notebook (in VSCode, this can be done by clicking the big restart button). Kernel crashing is most likely not due to a biopython issue.

Try the following:

1. Create a new conda env: `conda create -n bio -c bioconda python=3.11 biopython jupyter`
2. Make a new notebook in VSC
3. Select the correct env (`bio`)
4. Run `import Bio` in a code cell.


Side note: Are you defining the `ProteinAtom` class in the same notebook? If you are, then you do not need to run `import ProteinAtom as PA` - this also does not make much sense as `ProteinAtom` is a class. If it is a module, then you should use camel case `protein_atom.py` and import like `from protein_atom import ProteinAtom as PA`.

**Comment by QGoy69** [comment]
Indeed the `import bio` works fine in the new bio environment. The problem is when I import ProteinAtom (which is a separate file `protein_atom.py`) in the notebook using `from protein_atom import ProteinAtom as PA`. I still get a kernel crash.
Here is the Jupyter log:

<img width="1592" height="228" alt="Image" src="https://github.com/user-attachments/assets/f8ba8f2c-c924-4389-a696-39235b060576" />

**Comment by OWissett** [comment]
Do you get a python error, or just a jupyter error?

**Comment by OWissett** [comment]
I don't think this an issue with Biopython. You would be better off making an issue on the jupyter or vscode notebook repos.

**Comment by QGoy69** [comment]
I only get a jupyter error. Thank you, I will consider asking on jupyter or vscode repos !
